### PR TITLE
Added Depth First Search in Every Language Article

### LINKED ISSUE #327: Add Depth First Search in Every Language Article
I realized that I'm playing with graph algorithms, but we never mentioned one of the most basic algorithms: dfs. Let's get a description going.

### PR DESCRIPTION
**Pull request by mowies**
### SOLUTION DESCRIPTION
This PR adds the article about depth first search in every language.

This PR resolves #327

### CODE REVIEW

**Review by jrg94 — CHANGES_REQUESTED** [review]
This is great! How would a program go about parsing the input? In the past, we used serialized adjacency matrices for graphs, and I was wondering if we could do something similar.

**Comment by mowies** [comment]
> This is great! How would a program go about parsing the input? In the past, we used serialized adjacency matrices for graphs, and I was wondering if we could do something similar.

Yes, I thought about that and didn't really come to a nice solution except for the one I pushed...

Do you mean like in the minimum spanning tree project [1] for example?

[1] https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/projects/minimum-spanning-tree/index.md#requirements

**Comment by mowies** [comment]
One problem I see in the adjacency matrix is that there is no clear way of adding data to the vertices. In order for a search program to be run on the graph/tree we need some vertex values to look for of course. So this would need to be added to the adjacency matrix in some form.

**Comment by mowies** [comment]
One way to adress this problem would be to have an additional input to programs that is the list of vertex values in the same order as they appear in the matrix.

**Comment by mowies** [comment]
@jrg94 I updated the article with requirements including an adjacency matrix now, please have a look :)

**Review by jrg94 — APPROVED** [review]
I'm trying to think if there is a cleaner way to represent the input, but this is probably as good as it's going to get from a parsing perspective (e.g. I'm thinking of lower level languages that might have to do a lot of work to process the input). If you're happy with this, I'll go ahead and merge it!

**Comment by jrg94** [comment]
Overall, I agree the adjacency matrix solution isn't great because it doesn't scale well. That said, the biggest issue is parsing, and I'm not sure there's a nice format beyond JSON or something like that.

**Comment by mowies** [comment]
I think I am happy with it so feel free to merge :)

**Pull request merged**
