### PR TITLE
Add Phix Language Article

### PR DESCRIPTION
**Pull request by rzuckerm**
Thanks for helping us build up our knowledge base! 
What kind of pull request have you brought us today?

## Pull Request Type

- [ ] Sample Program Documentation
- [x] Language Documentation
- [ ] Project Documentation
- [ ] Other (explain below)

## Notes

Feel free to share any details you feel are relevant.

### CODE REVIEW

**Review by jrg94 — APPROVED** [review]
Very nice! Excellent list of references.

**Review by jrg94 — CHANGES_REQUESTED** [review]
Whoops! Pushed accept too soon. I think this needs to be named index.md to be picked up correctly.

**Comment by rzuckerm** [comment]
> Whoops! Pushed accept too soon. I think this needs to be named index.md to be picked up correctly.

What needs to be named index.md? I looked at all the other language articles, and there are just two files in `sources/languages/<language>`:

- `description.md`
- `front_matter.md`

For example, see the [algol68 directory](https://github.com/TheRenegadeCoder/sample-programs-website/tree/main/sources/languages/algol68).

**Comment by jrg94** [comment]
Oh my bad again haha You're in good shape.

**Comment by rzuckerm** [comment]
I fixed #543

**Pull request merged**
