### PR TITLE
Modify Fibonacci in Every Language

### LINKED ISSUE #490: Modify Fibonacci in Every Language Article
The current [Fibonacci](https://sampleprograms.io/projects/fibonacci/) article has an error in the Testing section. For example, this entry:

| Description | Input | Output                                                  |
| --------------- | ------- | ------------------------------------------------- |
| Sample      | 5        | 1: 1<br>2: 2<br>3: 3<br>4: 4<br>5: 5 |

should be:

| Description | Input | Output                                                  |
| --------------- | ------- | ------------------------------------------------- |
| Sample      | 5        | 1: 1<br>2: 1<br>3: 2<br>4: 3<br>4: 5 |

### PR DESCRIPTION
**Pull request by rzuckerm**
Thanks for helping us build up our knowledge base! 
What kind of pull request have you brought us today?

## Pull Request Type

- [x] Sample Program Documentation
- [ ] Language Documentation
- [ ] Project Documentation
- [ ] Other (explain below)

## Notes

Feel free to share any details you feel are relevant.
fixes #490

### CODE REVIEW

**Comment by jrg94** [comment]
So weird! Most of the test examples are wrong.

**Comment by rzuckerm** [comment]
@jrg94 Which ones? Maybe I can help.

**Comment by jrg94** [comment]
Nevermind! You caught them all.

**Review by jrg94 — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
