### PR TITLE
Added Baklava in Kotlin Article

### PR DESCRIPTION
**Pull request by stuin**
Thanks for helping us build up our knowledge base! 
What kind of pull request hav you brought us today?

## Pull Request Type

- [x] Sample Program Documentation
- [ ] Language Documentation
- [ ] Project Documentation
- [ ] Other (explain below)

## Notes

Feel free to share any details you feel are relevant.

### CODE REVIEW

**Comment by stuin** [comment]
Fixes #192

**Review by jrg94 — APPROVED** [review]
Looks great! Any chance you'd want to help with the featured images? It's pretty easy to do. I usually just pick something from here: https://pixabay.com/

Then, you can drop the image in the assets/sources/ folder, and the CI will generate the titled image for you. (Don't forget to put the file name in the header here.)

**Comment by stuin** [comment]
Looks like it needs write access to generate all the images?

**Comment by jrg94** [comment]
Interesting! Is it because you added the files?

**Comment by jrg94** [comment]
I'm going to try rerunning it. If that doesn't work, I'll add you to core. If that doesn't work, I'll try committing as myself.

**Comment by jrg94** [comment]
Actually, this shouldn't be an issue since it commits to the current branch... hmmmm!

**Comment by jrg94** [comment]
Can you try pulling from master?

**Comment by stuin** [comment]
Error: Error: Pushing to https://github.com/TheRenegadeCoder/sample-programs-website
remote: Permission to TheRenegadeCoder/sample-programs-website.git denied to github-actions[bot].

**Comment by jrg94** [comment]
I saw that error, but the error I posted happens even before that. I think it's possibly a fork issue. I'll investigate a bit more.

**Comment by jrg94** [comment]
Can you try pulling from master once more?

**Comment by jrg94** [comment]
I really think this has something to do with you being on a fork. It looks like it's trying to push to Master on this repo despite the change being on your repo. That's why it can't find a commit to work from. I'll sent a bug report out to the author of the tool. Perhaps they can shed some light on it.

**Comment by jrg94** [comment]
I'm going to merge this. The website build will likely fail, so I will make a separate pull request with an additional source image.

**Pull request merged**
