### PR TITLE
Added the Hello World Article for Emojicode.

### PR DESCRIPTION
**Pull request by Bracciata**
Issue #247

### CODE REVIEW

**Review by Bracciata — COMMENTED** [review]
Fixed them in my latest commit. Thanks for catching that.

**Review by jrg94 — APPROVED** [review]
👍

**Comment by Bracciata** [comment]
@jrg94 can you mark this and my other pull requests with the topic hacktoberfest-accepted. Thank you!  Also if you would like me to ping you on those two just let me know!

**Comment by jrg94** [comment]
I'm not sure what rules you're referring too, but I did this yesterday: https://twitter.com/hacktoberfest/status/1312221208667185153?s=20

I assume all your pull requests should be good!

**Pull request merged**
