### PR TITLE
Created an article for FizzBuzz in C.

### PR DESCRIPTION
**Pull request by shubhragupta-code**
Created an article for FizzBuzz in C for issue #217 
If there are any changes, do tell them.

### CODE REVIEW

**Review by jrg94 — APPROVED** [review]
Very cool! Nice addition.

**Comment by shubhragupta-code** [comment]
Can you add label `hacktoberfest-accepted` to this pull request with respect to the updated hacktoberfest rules?

**Comment by jrg94** [comment]
This will still count for you even if we don't tag it. Your pull request got merged and approved.

**Comment by jrg94** [comment]
The only potential issue was that the repo didn't have the hacktoberfest tag when you made the pull request.

**Comment by shubhragupta-code** [comment]
But the rules on [hacktoberfest website](https://hacktoberfest.digitalocean.com/hacktoberfest-update) specify that

> We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are labeled as ‘hacktoberfest-accepted’ by a maintainer, or submitted in a repository classified with the ‘hacktoberfest’ topic.

> To put the rules in a form consistent with the spirit of Hacktoberfest:

    PRs count if:
    Submitted during the month of October AND
    Submitted in a public repo AND (
      The PR is labelled as hacktoberfest-accepted by a maintainer OR
      Submitted in a repo with the hacktoberfest topic AND (
        The PR is merged OR
        The PR has been approved
      )
    ) 

I submitted this pr on Oct 5. So, I think these rules apply to this pr.

**Comment by shubhragupta-code** [comment]
I logged in hacktoberfest website and both of my PRs are in review. Thanks for clearing my doubt.

**Pull request merged**
